a = input('Digite algo: ')
print('O tipo primitivo é', type(a))
print('É alfanumérico? {}'.format (a.isalnum()))
print('É alfabetico? {}'.format (a.isalpha()))
print('É numérico? {}'.format (a.isnumeric()))
print('So tem espaços? {}'.format (a.isspace()))
print('Ésta em letras maiúsculas?', a.isupper())
print ('Ésta em letras minúsculas?', a.islower())
print('Ésta capitalizada?', a.istitle())